baseURL: "https://staticprime.com"
build:
  writeStats: true
minify:
  disableXML: true
  minifyOutput: true
caches:
  assets:
    dir: ":resourceDir/_gen"
    maxAge: "720h"
security:
  enableInlineShortcodes: false
